"""Configuration models for generated Django projects."""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Literal

DatabaseBackend = Literal["sqlite", "postgres"]
TemplatePreset = Literal["minimal", "api", "fullstack"]


def slugify_name(value: str) -> str:
    """Return a safe Python package and directory name."""
    import re

    slug = re.sub(r"[^a-zA-Z0-9_]+", "_", value.strip().lower())
    slug = re.sub(r"_+", "_", slug).strip("_")
    if not slug:
        return "django_project"
    if slug[0].isdigit():
        slug = f"project_{slug}"
    return slug


@dataclass(frozen=True)
class ProjectConfig:
    """All choices needed to render a project."""

    project_name: str = "django_project"
    description: str = "A small Django project generated by djforge."
    preset: TemplatePreset = "minimal"
    database: DatabaseBackend = "sqlite"
    include_api: bool = False
    include_docker: bool = False
    include_env: bool = True
    include_pytest: bool = True

    @property
    def slug(self) -> str:
        return slugify_name(self.project_name)

    @property
    def package_name(self) -> str:
        return self.slug

    @property
    def uses_postgres(self) -> bool:
        return self.database == "postgres"

    @property
    def requirements(self) -> list[str]:
        packages = ["Django>=5.0,<6.0", "django-environ>=0.11"]
        if self.include_api:
            packages.append("djangorestframework>=3.15")
        if self.uses_postgres:
            packages.append("psycopg[binary]>=3.1")
        if self.include_pytest:
            packages.extend(["pytest>=8", "pytest-django>=4.8"])
        return packages

    def with_name(self, name: str) -> ProjectConfig:
        return replace(self, project_name=name)


PRESETS: dict[TemplatePreset, ProjectConfig] = {
    "minimal": ProjectConfig(
        preset="minimal",
        database="sqlite",
        include_api=False,
        include_docker=False,
    ),
    "api": ProjectConfig(
        preset="api",
        database="sqlite",
        include_api=True,
        include_docker=False,
    ),
    "fullstack": ProjectConfig(
        preset="fullstack",
        database="postgres",
        include_api=True,
        include_docker=True,
    ),
}
